### ISSUE TITLE
Inform for qb64: compilation error

### ISSUE THREAD

**Issue by SayedSakka** [FellippeHeitor/InForm#1]
Dear Sir
I followed the steps to try inform for qb64, but I am afraid I am stuck:
when went to qb64, t gives me errors for the generated code (login.bas), with the external modules:

': External modules: ---------------------------------------------------------------
'$INCLUDE:'InForm\InForm.ui'
'$INCLUDE:'InForm\xp.uitheme'
'$INCLUDE:'login.frm'

![error](https://cloud.githubusercontent.com/assets/24807569/21519275/7db6149a-ccf4-11e6-800b-cdcdecb3f0cc.jpg)

Thankx

**Comment by FellippeHeitor** [comment]
Hello.

You have a **very outdated** version of QB64 (I can see it even without asking you to go to Help->About, because the _Find_ field is on the top of the window, and in newer versions it's been moved down a while back).

So the first thing to do is to **download the latest version of QB64** (from www.qb64.org). Line 27 of InForm.ui is giving you problems because it requires QB64's precompiler metacommands, which didn't exist when the version you have was released in 2015.

Thanks for trying InForm and please let me know how it works for you after you upgrade to QB64 1.1

**Comment by FellippeHeitor** [comment]
Hello.

You have a very outdated version of QB64 (I can see it even without asking
you to go to Help->About, because the *Find* field is on the top of the
window, and in newer versions it's been moved down a while back).

So the first thing to do is to download the latest version of QB64 (from
www.qb64.org or www.qb64.net). Line 27 of InForm.ui is giving you problems
because it requires QB64's precompiler metacommands, which didn't exist
when the version you have was released in 2015.

Thanks for trying InForm and please let me know how it works for you after
you upgrade to QB64 1.1

2016-12-28 7:55 GMT-02:00 SayedSakka <notifications@github.com>:

**Comment by SayedSakka** [comment]
Thanks a lot for your prompt feedback 
I will update qb64 and update you

Again thank you very much

Yours
S. A. Sakka



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by SayedSakka** [comment]
Thanks a lot, it worked perfectly

**Comment by FellippeHeitor** [comment]
I'm glad to hear it! Looking forward to seeing what you'll come up with using InForm.

All the best!
Fellippe.

**Comment by SayedSakka** [comment]
Dear Mr.  Fellippe Heitor
Thanks for your caring. 
Right now I am trying to use Inform with some programs I already have written in qb64
But uses menus writtin as well in qb64, as step one I am replacing the old menus with Inform as a test but I noticed the following:
- all forms generated by Inform have icon of qb64,  though qb64 programs don't,  so I wonder if you can Change the icon to be Inform logo or non. 
- when I call a sub/fun the image of the caller form,  still displayed
I tried to use _FREEIMAGE but unfortunately couldn't solve this issue. 

Thanks in advance
 Best regards

S. Sakka



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by FellippeHeitor** [comment]
- You can manually bypass the icon statement in the **InForm.ui** file.  Look in SUB _**__UI_Init**_ and delete or comment out the **_ICON** line.

- What type of program are you creating? Is it a graphic program? Because if it is, you should add a PictureBox control to the main window and do all the drawing in there. Here's how: https://github.com/FellippeHeitor/InForm/wiki/Picture-box#using-picturebox-as-a-drawing-surface

**Comment by SayedSakka** [comment]
Thanks a lot for your prompt feedback

I will follow your advice and let you know

Thanks again

My best regards

S. Sakka



Sent from my Samsung Galaxy smartphone.

-------- Original message --------
