### ISSUE TITLE
Question: is there a way to drag and drop files onto a text box and have its filename/path showup? 

### ISSUE THREAD

**Issue by Weej1** [FellippeHeitor/InForm#106]
Hi Fellippe

I'm trying to get my head around InForm and I was wondering if Drag n drop worked in the manner described in the title? My idea is to make a frontend for ffmpeg to batch convert videos, it's very basic (pun!) but the idea was if the user had like 5 files in a directory, they'd drag and drop it onto a textbox like area and then each filename (and path of each file?) would show up. 

the app would then apply the necessary ffmpeg switches and such to each file name loaded. Is this at all possible with Inform ? Do let me know!

**Comment by FellippeHeitor** [comment]
Hi there, @Weej1.

If you're using QB64 v1.3 or up on Windows, you can do that easily.

In your __UI_OnLoad event, add a call to _ACCEPTFILEDROP. That'll allow your program to receive files via drag and drop onto its window.

Then, to check if any files were dropped, you check whether _TOTALDROPPEDFILES is greater than 0. If so, you can use the _DROPPEDFILE$() array to read the list of dropped files and work on them. When you're done, call _FINISHDROP so that your program can start listening to drop events again.

If you want all that processing to only happen if a certain textbox has focus, you can check whether __UI_FocusID = YourControlID before processing the dropped files. Other wise you can just check for the drop in your __UI_BeforeUpdateDisplay event and then fill Text(YourControlID) with _DROPPEDFILE$(1), then _FINISHDROP.

More about these QB64 statements in the below:
- http://www.qb64.org/wiki/ACCEPTFILEDROP
- http://www.qb64.org/wiki/TOTALDROPPEDFILES
- http://www.qb64.org/wiki/DROPPEDFILE
- http://www.qb64.org/wiki/FINISHDROP

**Comment by FellippeHeitor** [comment]
BTW, that's how you can drop a .frm file onto UiEditor too.
